spring:
  datasource:
    url: jdbc:mysql://mysql-db:3306/hotel_management_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: ${MYSQL_USER:hoteluser}
    password: ${MYSQL_PASSWORD:hotelpass}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:hotelManagementDockerSecretKey2024}
  expiration: ${JWT_EXPIRATION:86400000}

logging:
  level:
    com.hotelmanagement: INFO
    org.springframework.security: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /app/logs/hotel-management.log

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
