spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_management_dev?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.hotelmanagement: DEBUG
    org.springframework.security: DEBUG
