spring:
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/hotel_management_prod}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    com.hotelmanagement: INFO
    org.springframework.security: WARN
